"""Contract tests for bacdive_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from bacdive_weaver import vocab
from bacdive_weaver.factory import build_bacdive_weaver_fixture

_MANIFEST = vocab.build_manifest(backends=("api",))


class TestApiOrder(WeaverOrderContractTests):
    capability_id = "resolve_traits"
    minimal_outputs = frozenset({"microbe.trait.cell_shape"})
    backend = "api"

    def make_weaver(self):
        # Fixture-backed (offline): the keyless API backend is always configured,
        # so there is nothing to skip — but we must not hit the live service.
        return build_bacdive_weaver_fixture()

    def sample_strand_sets(self):
        # Real, distinct species names. Only E. coli resolves in the fixture; the
        # rest are clean misses — the order contract only checks 1:1 alignment.
        samples = [
            {"organism.scientific_name": "Escherichia coli"},
            {"organism.scientific_name": "Bacillus subtilis"},
            {"organism.scientific_name": "Staphylococcus aureus"},
            {"organism.scientific_name": "Pseudomonas aeruginosa"},
            {"organism.scientific_name": "Lactobacillus acidophilus"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestResolveTraitsCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("resolve_traits")
    consumed_values_a = {"organism.scientific_name": "Escherichia coli"}
    consumed_values_b = {"organism.scientific_name": "sample-b-organism.scientific_name"}
    group_subset = "morphology"
    group_superset = "physiology"
