"""Contract tests for gmrepo_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from gmrepo_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("local",))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = getattr(factory, "build_gmrepo_weaver_fixture", None) or factory.build_gmrepo_weaver
    return builder()


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "gmrepo.list_abundances"
    minimal_outputs = frozenset({"microbe.abundance.associations"})
    backend = "local"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # Real, distinct NCBI taxids (816/216851 are in the fixture; the rest miss cleanly).
        samples = [
            {"ncbi.taxon.id": 816},
            {"ncbi.taxon.id": 216851},
            {"ncbi.taxon.id": 1350},
            {"ncbi.taxon.id": 838},
            {"ncbi.taxon.id": 1263},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestGmrepoListAbundancesCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("gmrepo.list_abundances")
    consumed_values_a = {"ncbi.taxon.id": 816}
    consumed_values_b = {"ncbi.taxon.id": "sample-b-ncbi.taxon.id"}
    group_subset = "summary"
    group_superset = "associations"
