"""Contract tests for wikidata_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from wikidata_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("api",))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = (
        getattr(factory, "build_wikidata_weaver_fixture", None) or factory.build_wikidata_weaver
    )
    return builder()


class TestApiOrder(WeaverOrderContractTests):
    capability_id = "resolve_taxon"
    minimal_outputs = frozenset({"organism.vernacular_names"})
    backend = "api"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        samples = [
            {"organism.scientific_name": "Ursus arctos"},
            {"organism.scientific_name": "Panthera leo"},
            {"organism.scientific_name": "Felis catus"},
            {"organism.scientific_name": "Corvus corax"},
            {"organism.scientific_name": "Vulpes vulpes"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestResolveTaxonCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("resolve_taxon")
    consumed_values_a = {"organism.scientific_name": "Ursus arctos"}
    consumed_values_b = {"organism.scientific_name": "sample-b-organism.scientific_name"}
    group_subset = "core"
    group_superset = "names"
