"""Contract tests for mondo_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from mondo_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("local",))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = getattr(factory, "build_mondo_weaver_fixture", None) or factory.build_mondo_weaver
    return builder()


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "mondo.lookup_by_mesh"
    minimal_outputs = frozenset({"disease.mondo.id"})
    backend = "local"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # TODO: replace with >=5 real, distinct inputs from the source.
        samples = [
            {"disease.mesh.id": "D003093"},
            {"disease.mesh.id": "D003092"},
            {"disease.mesh.id": "D015212"},
            {"disease.mesh.id": "D004066"},
            {"disease.mesh.id": "D999999"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestMondoLookupByMeshCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("mondo.lookup_by_mesh")
    consumed_values_a = {"disease.mesh.id": "D003093"}
    consumed_values_b = {"disease.mesh.id": "sample-b-disease.mesh.id"}
    group_subset = "term"
    group_superset = "ancestors"


class TestMondoLookupByMeddraCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("mondo.lookup_by_meddra")
    consumed_values_a = {"disease.meddra.id": "sample-a-disease.meddra.id"}
    consumed_values_b = {"disease.meddra.id": "sample-b-disease.meddra.id"}
    group_subset = "term"
    group_superset = "ancestors"
