"""Contract tests for disbiome_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit (then wired to the fixture). The order tests execute the
fixture-backed weaver over distinct taxids; the cache-key tests are pure. Do not
weaken these — they are the framework contract.
"""

from __future__ import annotations

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from disbiome_weaver import vocab
from disbiome_weaver.factory import build_disbiome_weaver_fixture

_MANIFEST = vocab.build_manifest(backends=("local",))


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "disbiome.list_diseases"
    minimal_outputs = frozenset({"microbe.disease.associations"})
    backend = "local"

    def make_weaver(self):
        # Fixture-backed so the order contract runs deterministically offline.
        return build_disbiome_weaver_fixture()

    def sample_strand_sets(self):
        # Distinct taxids: two are fixture hits (1591, 1350), the rest miss. The
        # order contract only requires one result per input, in order (a miss is a
        # valid result), so this exercises length + ordering across hits and misses.
        samples = [1591, 1350, 562, 9606, 99999]
        return [
            StrandSet.from_strands(f"e{i}", [Strand("ncbi.taxon.species_id", taxid)])
            for i, taxid in enumerate(samples)
        ]


class TestDisbiomeResolveDiseasesCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("disbiome.list_diseases")
    consumed_values_a = {"ncbi.taxon.species_id": 1591}
    consumed_values_b = {"ncbi.taxon.species_id": "sample-b-ncbi.taxon.species_id"}
    group_subset = "summary"
    group_superset = "associations"
