"""Contract tests for disbiome_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from disbiome_weaver import vocab
from disbiome_weaver.factory import build_disbiome_weaver

_MANIFEST = vocab.build_manifest(backends=("local",))


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "disbiome.resolve_diseases"
    minimal_outputs = frozenset({"microbe.disease.associations"})
    backend = "local"

    def make_weaver(self):
        weaver = build_disbiome_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # TODO: replace with >=5 real, distinct inputs from the source.
        samples = [
            {"ncbi.taxon.id": 1591},
            {"ncbi.taxon.id": "sample-0"},
            {"ncbi.taxon.id": "sample-1"},
            {"ncbi.taxon.id": "sample-2"},
            {"ncbi.taxon.id": "sample-3"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestDisbiomeResolveDiseasesCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("disbiome.resolve_diseases")
    consumed_values_a = {"ncbi.taxon.id": 1591}
    consumed_values_b = {"ncbi.taxon.id": "sample-b-ncbi.taxon.id"}
    group_subset = "summary"
    group_superset = "associations"
