"""Contract tests for agora_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from agora_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("local",))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = getattr(factory, "build_agora_weaver_fixture", None) or factory.build_agora_weaver
    return builder()


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "describe_metabolic_reconstruction"
    # core is always answerable offline (bundled crosswalk); the reactions repertoire
    # needs the reaction DB, so the always-available core key is the order-contract probe.
    minimal_outputs = frozenset({"microbe.metabolism.reconstruction"})
    backend = "local"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # Real, distinct taxids from the bundled AGORA2 crosswalk.
        samples = [
            {"ncbi.taxon.id": "592010"},
            {"ncbi.taxon.id": "1120917"},
            {"ncbi.taxon.id": "329726"},
            {"ncbi.taxon.id": "258515"},
            {"ncbi.taxon.id": "879566"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestDescribeMetabolicReconstructionCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("describe_metabolic_reconstruction")
    consumed_values_a = {"ncbi.taxon.id": "592010"}
    consumed_values_b = {"ncbi.taxon.id": "sample-b-ncbi.taxon.id"}
    group_subset = "core"
    group_superset = "reactions"
