"""Contract tests for wikipedia_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import WeaverOrderContractTests

from wikipedia_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("api",))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = (
        getattr(factory, "build_wikipedia_weaver_fixture", None) or factory.build_wikipedia_weaver
    )
    return builder()


class TestApiOrder(WeaverOrderContractTests):
    capability_id = "describe_pageviews"
    minimal_outputs = frozenset({"wikipedia.pageviews"})
    backend = "api"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        samples = [
            {"wikipedia.title": "Brown_bear"},
            {"wikipedia.title": "Lion"},
            {"wikipedia.title": "Cat"},
            {"wikipedia.title": "Common_raven"},
            {"wikipedia.title": "Red_fox"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


# NOTE: capability 'describe_pageviews' has <2 output groups, so CacheFingerprintTests
# (which exercise group subset/superset cache lookups) are not generated for it.
