"""Contract tests for faprotax_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import WeaverOrderContractTests

from faprotax_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("local",))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = (
        getattr(factory, "build_faprotax_weaver_fixture", None) or factory.build_faprotax_weaver
    )
    return builder()


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "describe_ecology"
    minimal_outputs = frozenset({"microbe.ecology.functional_groups"})
    backend = "local"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # Real, distinct lineages (minimal {name} entries, as ncbi_weaver emits):
        # four hits across different functions plus one deliberate miss.
        samples = [
            {"ncbi.taxon.lineage": [{"name": "Methylococcaceae"}, {"name": "Methylococcus"}]},
            {"ncbi.taxon.lineage": [{"name": "Desulfovibrionaceae"}, {"name": "Desulfovibrio"}]},
            {
                "ncbi.taxon.lineage": [
                    {"name": "Methanobacteriaceae"},
                    {"name": "Methanobrevibacter"},
                ]
            },
            {"ncbi.taxon.lineage": [{"name": "Lactobacillaceae"}, {"name": "Lactobacillus"}]},
            {"ncbi.taxon.lineage": [{"name": "Rhizobiaceae"}, {"name": "Rhizobium"}]},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


# NOTE: capability 'describe_ecology' has <2 output groups, so CacheFingerprintTests
# (which exercise group subset/superset cache lookups) are not generated for it.
