"""Contract tests for example_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from example_weaver import vocab
from example_weaver.factory import build_example_weaver

_MANIFEST = vocab.build_manifest(backends=("local",))


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "resolve_traits"
    minimal_outputs = frozenset({"microbe.trait.gram_stain"})
    backend = "local"

    def make_weaver(self):
        weaver = build_example_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # TODO: replace with >=5 real, distinct inputs from the source.
        samples = [
            {"ncbi.taxon.id": "562"},
            {"ncbi.taxon.id": "1423"},
            {"ncbi.taxon.id": "sample-0"},
            {"ncbi.taxon.id": "sample-1"},
            {"ncbi.taxon.id": "sample-2"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestResolveTraitsCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("resolve_traits")
    consumed_values_a = {"ncbi.taxon.id": "562"}
    consumed_values_b = {"ncbi.taxon.id": "sample-b-ncbi.taxon.id"}
    group_subset = "traits.core"
    group_superset = "traits.growth"
