"""Contract tests for uniprot_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from uniprot_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("api",))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = getattr(factory, "build_uniprot_weaver_fixture", None) or factory.build_uniprot_weaver
    return builder()


class TestApiOrder(WeaverOrderContractTests):
    capability_id = "resolve_protein"
    minimal_outputs = frozenset({"ncbi.taxon.id"})
    backend = "api"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # TODO: replace with >=5 real, distinct inputs from the source.
        samples = [
            {"protein.query": "TP53"},
            {"protein.query": "sample-0"},
            {"protein.query": "sample-1"},
            {"protein.query": "sample-2"},
            {"protein.query": "sample-3"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestResolveProteinCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("resolve_protein")
    consumed_values_a = {"protein.query": "TP53"}
    consumed_values_b = {"protein.query": "sample-b-protein.query"}
    group_subset = "identity"
    group_superset = "taxonomy"
