"""Contract tests for gtdb_weaver — execute_batch order/length + cache-key rules.

Generated by weaverkit. The order tests execute the weaver and SKIP until a
backend is configured; the cache-key tests are pure and run immediately. Do not
weaken these — they are the framework contract. Replace the synthesized sample
inputs below with real, distinct inputs from the source.
"""

from __future__ import annotations

import pytest

from braidworks.core import Strand, StrandSet
from braidworks.testing.contract import CacheFingerprintTests, WeaverOrderContractTests

from gtdb_weaver import factory, vocab

_MANIFEST = vocab.build_manifest(backends=("local", "api"))


def _build_weaver():
    # Prefer the offline fixture builder once you add it, so these run
    # deterministically; until then fall back to the introspection builder
    # (the order test then skips while the backend is unconfigured).
    builder = getattr(factory, "build_gtdb_weaver_fixture", None) or factory.build_gtdb_weaver
    return builder()


class TestLocalOrder(WeaverOrderContractTests):
    capability_id = "describe_gtdb_taxonomy"
    minimal_outputs = frozenset({"gtdb.lineage"})
    backend = "local"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # Real, distinct inputs from the bundled fixture crosswalk (+ a name).
        samples = [
            {"ncbi.taxon.id": "562"},
            {"organism.scientific_name": "Escherichia coli"},
            {"ncbi.taxon.id": "2053517"},
            {"ncbi.taxon.id": "41978"},
            {"ncbi.taxon.id": "3048838"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestLocalTreePlacementOrder(WeaverOrderContractTests):
    capability_id = "describe_gtdb_tree_placement"
    minimal_outputs = frozenset({"gtdb.tree.rootpath"})
    backend = "local"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # Real, distinct inputs whose species reps are leaves of the fixture tree.
        samples = [
            {"ncbi.taxon.id": "562"},
            {"organism.scientific_name": "Escherichia coli"},
            {"ncbi.taxon.id": "2053517"},
            {"ncbi.taxon.id": "41978"},
            {"ncbi.taxon.id": "3048838"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestApiOrder(WeaverOrderContractTests):
    capability_id = "describe_gtdb_taxonomy"
    minimal_outputs = frozenset({"gtdb.lineage"})
    backend = "api"

    def make_weaver(self):
        weaver = _build_weaver()
        strat = weaver._backends.get(self.backend)
        if strat is None or not strat.is_configured():
            pytest.skip(f"backend {self.backend!r} not configured")
        return weaver

    def sample_strand_sets(self):
        # Real, distinct inputs from the bundled fixture crosswalk (+ a name).
        samples = [
            {"ncbi.taxon.id": "562"},
            {"organism.scientific_name": "Escherichia coli"},
            {"ncbi.taxon.id": "2053517"},
            {"ncbi.taxon.id": "41978"},
            {"ncbi.taxon.id": "3048838"},
        ]
        return [
            StrandSet.from_strands(f"e{i}", [Strand(t, v) for t, v in values.items()])
            for i, values in enumerate(samples)
        ]


class TestDescribeGtdbTaxonomyCacheFingerprint(CacheFingerprintTests):
    capability = _MANIFEST.capability("describe_gtdb_taxonomy")
    consumed_values_a = {"ncbi.taxon.id": "562"}
    consumed_values_b = {"ncbi.taxon.id": "sample-b-ncbi.taxon.id"}
    group_subset = "core"
    group_superset = "lineage"
